#!/bin/bash

http_code=200
mime=text/html

while test $# -gt 0; do
    case $1 in 
        2* | 3* | 4* | 5* )
            # echo "set http code to $1"
            http_code=$1
        ;;
        --mime )
            shift
            mime=$1
        ;;
        * )
            break
        ;;
    esac
    shift
done

echo -e "HTTP/1.1 $http_code OK\r"
echo "Content-type: $mime"
echo

while read line
do
    echo $line
done
